# Generated by Django 4.2.1 on 2023-06-01 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post1',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
